# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my_resume',
                'doc_host': 'https://apereiral.github.io',
                'git_url': 'https://github.com/apereiral/my_resume',
                'lib_path': 'my_resume'},
  'syms': {'my_resume.core': {'my_resume.core.foo': ('core.html#foo', 'my_resume/core.py')}}}
